---
name: Type check
on:
  pull_request: ~
  push:
    branches:
      - main
      - master
jobs:
  typecheck:
    name: Type check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Neovim Typecheck linter
        uses: stevearc/nvim-typecheck-action@v1
        with:
          path: lua
          level: Information
          configpath: ".luarc.json"
          neodev-version: stable
  luacheck:
    name: Lua check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Luacheck linter
        uses: lunarmodules/luacheck@v1
        with:
          args: lua --config .luacheckrc
