---
name: Type check
on:
  pull_request: ~
  push:
    branches:
      - main
      - master

jobs:
  build:
    name: Type check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: stevearc/nvim-typecheck-action@v1
        with:
          path: lua
          level: Information
          configpath: ".luarc.json"
          neodev-version: nightly
          nvim-version: v0.9.1
          luals-version: 3.6.25
